Agrega opción para mostrar el modal en el checkout
mobbexco/woocommerce pull request #185
Opened 2023-03-25 06:46 UTC by leandroprz

2023-03-25 06:48 UTC, leandroprz commented on assets/css/checkout.css
> +    max-height: 2.500em;
Dejando `1.618em` se achata el logo.

2023-04-06 00:15 UTC, jlmobbex requested changes

2023-04-06 00:15 UTC, jlmobbex commented on utils/config-options.php
> +    'financial_widget_on_checkout' => [
Buenas! Si la adición del botón de "Ver financiación" se hace mediante un shortcode esta opción queda sin efecto. En caso contrario, habría que añadir un hook para que se añada automáticamente cuando se encuentre activa.

2023-08-24 20:52 UTC, jlmobbex commented
Cierro esta PR por inactividad, y porque que faltan cambios importantes en su funcionamiento para poder mergearse.

2023-08-24 20:52 UTC, closed without merging