[ECO-362] Force the use of dni field.
mobbexco/woocommerce pull request #210
Opened 2023-06-12 15:20 UTC by EMunozMobbex

2023-06-23 02:56 UTC, jlmobbex requested changes

2023-06-23 02:56 UTC, jlmobbex commented on Model/Config.php
> +        $saved_values[$name] = $value;
Para no tener que volver a obtener las opciones desde base de datos, y para mantener `$this->settings` actualizado se puede hacer un `$this->settings[$name] = $value`, en vez de llamar de nuevo a `get_settings`, y luego en el `update_option` del return pasar `$this->settings`.

También hay que actualizar la propiedad usando `$this->{$name}`.

2023-08-15 20:37 UTC, mobbexLuis approved these changes

2023-08-24 20:47 UTC, jlmobbex commented
Por ahora, dejamos pausada esta funcionalidad hasta que se defina como avanzar con la obligatoriedad del campo.

2023-09-20 14:18 UTC, closed without merging

2023-09-20 14:18 UTC, jlmobbex commented
Se decidió que no se continuará el desarrollo de esta feature.