Now check the directory where the file is located is correct
mobbexco/woocommerce pull request #219
Opened 2023-09-12 16:05 UTC by mobbexLuis

2023-09-12 19:18 UTC, EMunozMobbex approved these changes

2023-09-13 13:56 UTC, jlmobbex requested changes
Esto no corrige el error porque al principio del archivo se sigue incluyeno el archivo del autoload, haciendo que se arroje un fatal error. El cambio que se metió no modifica tampoco el efecto de la condición, sigue siendo el mismo. Hacer pruebas instalando antes de subir los cambios

2023-09-15 12:26 UTC, mobbexLuis commented
@jlmobbex entonces el flujo deberia cortarse antes del require?
Por otro lado, el cambio fue probado y ahora detecta el error en base al directorio. Antes se "bypasseaba" porque tomaba como condicion el nombre del archivo que es el mismo en master y release.

2023-09-15 21:51 UTC, jlmobbex approved these changes

2023-09-15 21:52 UTC, merged