Fix success redirects adding onPayment
mobbexco/woocommerce pull request #234
Opened 2023-11-15 14:26 UTC by mobbexLuis

2023-11-16 18:56 UTC, EMunozMobbex approved these changes

2023-11-17 23:43 UTC, jlmobbex requested changes

2023-11-17 23:43 UTC, jlmobbex commented on assets/js/mobbex.bootstrap.js
> +                location.href = response.return_url + '&fromCallback=onError&status=500';
Es necesario este redirect teniendo en cuenta el `handleErrorResponse`? Desde ahí se debería mostrar el error según entiendo

2023-11-24 18:44 UTC, jlmobbex approved these changes

2023-11-24 18:44 UTC, merged