[ECO-579] Add mobbex banner in checkout
mobbexco/woocommerce pull request #236
Opened 2023-11-16 15:17 UTC by EMunozMobbex

2023-11-17 23:52 UTC, jlmobbex requested changes

2023-11-17 23:52 UTC, jlmobbex commented on assets/js/mobbex.bootstrap.js
> +    $(document).on('change', '.mbbx-banner-input', () => $('.mobbex-banner').toggleClass("mobbex-hidden"));
Si viene la opción seleccionada por defecto el hidden va a estar revertido. Debería chequearse con un `if` si está seleccionada en vez de hacer un `toggleClass` para evitar esto

2023-11-21 14:26 UTC, EMunozMobbex commented on assets/js/mobbex.bootstrap.js
> +    $(document).on('change', '.mbbx-banner-input', () => $('.mobbex-banner').toggleClass("mobbex-hidden"));
La linea de arriba chequea previamente si input vino como  checked y le quita la clase en caso de que asi sea, por lo que no deberia haber un problema si viene como checked

2023-11-23 13:50 UTC, mobbexLuis approved these changes

2023-11-24 18:52 UTC, jlmobbex approved these changes

2023-11-24 18:52 UTC, merged