[ECO-729] Improved Mobbex plans obtaining.
mobbexco/woocommerce pull request #240
Opened 2023-12-14 15:09 UTC by EMunozMobbex

2023-12-18 12:39 UTC, mobbexLuis approved these changes

2023-12-18 15:01 UTC, mobbexLuis approved these changes

2023-12-26 15:26 UTC, jlmobbex requested changes

2023-12-26 15:26 UTC, jlmobbex commented on Model/Config.php
> +    private function maybe_decode($plans)
`maybe_decode` debería ser utilizable con cualquier string, por lo que la variable `$plans` quizás sería mejor que se llame `$input` o `$metadata`, por ejemplo.

2024-01-03 17:42 UTC, mobbexLuis approved these changes

2024-01-04 11:14 UTC, jlmobbex approved these changes

2024-01-04 11:15 UTC, merged