[ECO-1079] Fix coupons do not apply to setup fee
mobbexco/woocommerce pull request #272
Opened 2024-08-15 19:48 UTC by mobbexLuis

2024-08-27 13:30 UTC, EMunozMobbex requested changes

2024-08-27 13:30 UTC, EMunozMobbex commented on Helper/Order.php
> +            $this->order->get_items() ?: [],
Una sugerencia para esta parte del código:

```php
<?php
$order_items = $this->order->get_items() ?: [];

foreach(['fee', 'coupon', 'shipping'] as $itemType){
    if($this->order->get_items($itemType))
        $order_items[] = $this->order->get_items($itemType);
}

if($order_items)
    $this->manage_items($order_items, $checkout);
```
La razón de la sugerencia es que me un poco intrincado que estés metiendo arrays dentro de arrays y tengas que forechear 2 veces para acceder a los valores, se puede resolver de otras maneras , yo dejo esa sugerencia, pero el punto es que me parece que `$order_items` deberia ser un array de items y no un array de arrays.

2024-08-27 13:30 UTC, EMunozMobbex commented on Helper/Order.php
> +                    $this->cart_fee = $item->get_total();
Veo que este valor se guarda pero no veo que se use en ninguna parte, donde se usa?

2025-02-14 14:38 UTC, jlmobbex commented
Esto se integrará de otra forma más completa en la verisión 4.0 del plugin.

2025-02-14 14:38 UTC, closed without merging